function MO_JOBS_autoUpdater():

    set {_version?::*} to url "https://raw.githubusercontent.com/CaptainGarih/CastleCraft/main/captaingarih/public/MoJobs/mojobs_version.txt" contents
    if {mojobs.api.version?} is not "%{_version?::*}%":

        broadcast "&aMo' Jobs system update... &7Mo' Jobs by CaptainGarih (antoine.pelka.fr)"
        wait 2 ticks

        set {_file} to "jobs_main.sk"
        broadcast "&aUPDATING &f%{_file}%..."
        if file "/home/container/plugins/Skript/scripts/%{_file}%" exists:

            delete file "/home/container/plugins/Skript/scripts/%{_file}%"
            wait 5 ticks
            broadcast "&aUPDATE &fdownloading file %{_file}%..."
            download file from "https://raw.githubusercontent.com/CaptainGarih/CastleCraft/main/captaingarih/public/MoJobs/latest/%{_file}%" to file "/home/container/plugins/Skript/scripts/%{_file}%"
        
        set {_file} to "jobs_farmer.sk"
        if file "/home/container/plugins/Skript/scripts/%{_file}%" exists:

            delete file "/home/container/plugins/Skript/scripts/%{_file}%"
            wait 5 ticks
            broadcast "&aUPDATE &fdownloading file %{_file}%..."
            download file from "https://raw.githubusercontent.com/CaptainGarih/CastleCraft/main/captaingarih/public/MoJobs/latest/%{_file}%" to file "/home/container/plugins/Skript/scripts/%{_file}%"
        
        set {_file} to "jobs_miner.sk"
        if file "/home/container/plugins/Skript/scripts/%{_file}%" exists:

            delete file "/home/container/plugins/Skript/scripts/%{_file}%"
            wait 5 ticks
            broadcast "&aUPDATE &fdownloading file %{_file}%..."
            download file from "https://raw.githubusercontent.com/CaptainGarih/CastleCraft/main/captaingarih/public/MoJobs/latest/%{_file}%" to file "/home/container/plugins/Skript/scripts/%{_file}%"
        
        set {_file} to "jobs_hunter.sk"
        if file "/home/container/plugins/Skript/scripts/%{_file}%" exists:

            delete file "/home/container/plugins/Skript/scripts/%{_file}%"
            wait 5 ticks
            broadcast "&aUPDATE &fdownloading file %{_file}%..."
            download file from "https://raw.githubusercontent.com/CaptainGarih/CastleCraft/main/captaingarih/public/MoJobs/latest/%{_file}%" to file "/home/container/plugins/Skript/scripts/%{_file}%"

        set {_file} to "jobs_lumberjack.sk"
        if file "/home/container/plugins/Skript/scripts/%{_file}%" exists:

            delete file "/home/container/plugins/Skript/scripts/%{_file}%"
            wait 5 ticks
            broadcast "&aUPDATE &fdownloading file %{_file}%..."
            download file from "https://raw.githubusercontent.com/CaptainGarih/CastleCraft/main/captaingarih/public/MoJobs/latest/%{_file}%" to file "/home/container/plugins/Skript/scripts/%{_file}%"

        wait 1 second



on load:

    MO_JOBS_autoUpdater()

every 1 minute:

    MO_JOBS_autoUpdater()